#include "wifi-portal.h"

const char wifi_portal_html[] =
    "<!doctype html>"
    "<html lang=\"en\"><head>"
    "<meta charset=\"utf-8\">"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
    "<title>ESP32-NUT Wi-Fi Setup</title>"
    "<style>"
    ":root{color-scheme:light dark;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}"
    "body{margin:0;background:#101418;color:#eef2f5}"
    "main{max-width:32rem;margin:0 auto;padding:2rem 1.25rem}"
    "section{background:#1b232b;border:1px solid #34424f;border-radius:1rem;padding:1.4rem}"
    "h1{font-size:1.55rem;margin:0 0 .5rem}p{line-height:1.45;color:#c8d2da}"
    "label{display:block;font-weight:600;margin-top:1rem}"
    "input,button{box-sizing:border-box;width:100%;font:inherit;border-radius:.65rem;padding:.8rem;margin-top:.4rem}"
    "input{border:1px solid #536473;background:#111820;color:#fff}"
    "button{border:0;background:#50b96b;color:#07120a;font-weight:700;margin-top:1.25rem}"
    "button:disabled{opacity:.55}.password-toggle{display:flex;align-items:center;gap:.55rem;margin-top:.65rem;font-weight:400}"
    ".password-toggle input{width:auto;margin:0}.password-toggle span{font-size:.95rem}.warning{color:#ffcb6b}.status{min-height:1.5rem}"
    "</style></head><body><main><section>"
    "<h1>ESP32-NUT Wi-Fi Setup</h1>"
    "<p class=\"warning\">This temporary setup network is open. Complete configuration promptly.</p>"
    "<form id=\"wifi-form\">"
    "<label for=\"ssid\">Wi-Fi network</label>"
    "<input id=\"ssid\" name=\"ssid\" list=\"networks\" maxlength=\"32\" required autocomplete=\"off\">"
    "<datalist id=\"networks\"></datalist>"
    "<label for=\"password\">Wi-Fi password</label>"
    "<input id=\"password\" name=\"password\" type=\"password\" maxlength=\"63\" autocomplete=\"off\">"
    "<label class=\"password-toggle\" for=\"show-password\"><input id=\"show-password\" type=\"checkbox\"><span>Show password</span></label>"
    "<button id=\"connect\" type=\"submit\">Connect</button>"
    "</form><p id=\"status\" class=\"status\" role=\"status\">Scanning for networks...</p><p id=\"diagnostic\" class=\"status\" role=\"status\"></p>"
    "</section></main><script>"
    "const form=document.getElementById('wifi-form'),button=document.getElementById('connect'),status=document.getElementById('status'),diagnostic=document.getElementById('diagnostic'),password=document.getElementById('password'),showPassword=document.getElementById('show-password');"
    "showPassword.addEventListener('change',()=>password.type=showPassword.checked?'text':'password');"
    "fetch('/api/networks').then(r=>r.json()).then(networks=>{"
    "const list=document.getElementById('networks');networks.forEach(name=>{const option=document.createElement('option');option.value=name;list.appendChild(option)});"
    "status.textContent=networks.length?'Select a network or enter a hidden network name.':'Enter the network name manually.';"
    "}).catch(()=>status.textContent='Enter the network name manually.');"
    "fetch('/api/status').then(r=>r.json()).then(result=>{diagnostic.textContent=result.message||''}).catch(()=>{});"
    "form.addEventListener('submit',async event=>{event.preventDefault();button.disabled=true;status.textContent='Saving credentials and restarting to test Wi-Fi...';"
    "try{const response=await fetch('/api/configure',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(form))});"
    "const result=await response.json();status.textContent=result.message;if(!response.ok)button.disabled=false;"
    "}catch(error){status.textContent='The device stopped responding. Rejoin the setup network and try again.';button.disabled=false;}});"
    "</script></body></html>";

const size_t wifi_portal_html_length = sizeof(wifi_portal_html) - 1;
